#!/bin/bash

# Phase 2 Quick Start Guide
# Fast reference for running Phase 2 tests

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                Phase 2 Testing - Quick Start Guide                 ║"
echo "╚════════════════════════════════════════════════════════════════════╝"

echo ""
echo -e "${BLUE}📋 PHASE 2 OVERVIEW${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Phase 2 tests the blockchain network under normal operating conditions."
echo "All 4 tasks must pass before proceeding to Phase 3 (Attack Simulation)."
echo ""

echo -e "${BLUE}✅ PREREQUISITES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Multi-node network running:"
echo "   bash start-multi-node.sh"
echo ""
echo "2. All nodes healthy:"
echo "   bash verify-multi-node.sh"
echo ""

echo -e "${BLUE}🚀 QUICK START OPTIONS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Option 1: Run ALL Phase 2 tests (recommended)"
echo "  bash test-phase2-all.sh"
echo ""
echo "Option 2: Run individual tasks"
echo "  Task 2.1 (Vote Propagation):        bash test-phase2-task2-1.sh"
echo "  Task 2.2 (Block Mining):            bash test-phase2-task2-2.sh"
echo "  Task 2.3 (Chain Sync):              bash test-phase2-task2-3.sh"
echo "  Task 2.4 (Network Recovery):        bash test-phase2-task2-4.sh"
echo ""

echo -e "${BLUE}📊 EXPECTED RESULTS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Task 2.1: Vote Transaction Propagation"
echo "  ✓ Vote propagation: <1 second"
echo "  ✓ Nodes with vote: 5/5 (100%)"
echo "  ✓ Data consistency: 100%"
echo ""
echo "Task 2.2: Block Mining and Consensus"
echo "  ✓ Validator mining: 3/3 success"
echo "  ✓ Observer restriction: Enforced"
echo "  ✓ Network sync: All nodes converged"
echo ""
echo "Task 2.3: Chain Synchronization"
echo "  ✓ Fresh node sync: Working"
echo "  ✓ Large chain sync: <10 seconds per 100 blocks"
echo "  ✓ Transaction preservation: 100%"
echo ""
echo "Task 2.4: Network Partition Recovery"
echo "  ✓ Partition detection: Working"
echo "  ✓ Fork resolution: Converged"
echo "  ✓ Data integrity: 0 loss"
echo ""

echo -e "${BLUE}⏱️  TIMING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Individual tests: ~10-15 minutes each"
echo "All Phase 2 tests: ~50 minutes total"
echo ""

echo -e "${BLUE}📁 OUTPUT FILES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Results saved to:"
echo "  PHASE2_TEST_RESULTS.md    - Comprehensive test report"
echo "  Project_Status/PHASE_2_COMPLETE.md - Detailed documentation"
echo ""

echo -e "${BLUE}🔍 MONITORING DURING TESTS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In another terminal, monitor network status:"
echo "  curl http://localhost:3001/network/status | jq"
echo ""
echo "Or watch individual node status:"
echo "  watch 'curl -s http://localhost:3001/node/status | jq .chainHeight'"
echo ""

echo -e "${BLUE}❌ TROUBLESHOOTING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If tests fail:"
echo ""
echo "1. Check network status"
echo "   bash verify-multi-node.sh"
echo ""
echo "2. View node logs"
echo "   docker-compose -f docker-compose.multi-node.yml logs -f blockchain-node-1"
echo ""
echo "3. Restart network"
echo "   docker-compose -f docker-compose.multi-node.yml down"
echo "   bash start-multi-node.sh"
echo ""
echo "4. Wait for stability"
echo "   sleep 30 && bash verify-multi-node.sh"
echo ""

echo -e "${BLUE}✨ NEXT STEPS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After all Phase 2 tests pass:"
echo ""
echo "1. Review PHASE2_TEST_RESULTS.md"
echo "2. Ensure all success criteria met"
echo "3. Backup network state (optional)"
echo "4. Proceed to Phase 3: Attack Simulation"
echo ""
echo "See: Project_Status/PHASE_2_COMPLETE.md for detailed info"
echo ""
