events { worker_connections 1024; }

http {
  upstream frontend_upstream { server frontend:5173; }
  upstream admin_panel_upstream { server admin-panel:5174; }
  upstream backend_upstream { server backend:3000; }

  server {
    listen 80;
    location / {
      proxy_pass http://frontend_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /admin/ {
      proxy_pass http://admin_panel_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/ {
      proxy_pass http://backend_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}